s3:
    bucket_name: 'horusxusafa'
    folder_name: 'pictures'

image_settings:
    horizontal_res: 640
    vertical_res: 480
    file_name: 'test'
    file_extension: 'jpg'
    folder_name: 'images'
    awb_mode: 'auto'
    photo_interval: 60

camera_info:
    location_name: 'location'
    camera_type: 'camera-type'
    camera_name: 'camera-no-1'

debug: true